from:
  - v2/options/deploy/commands

params:
  actions:
    Commands:
      deploy:
        post_blocks:
          dev:
            params:
              actions:
                - 'yarn'
                - 'yarn build'
  containers:
    common:
      build:
        params:
          from:
            - .params.options.containers.build.tools
      deploy:
        commands:
          params:
            post_blocks:
              - actions:
                - from: .params.actions.Commands.deploy.post_blocks.${context.environment}.execute
