from:
  - v2/options/deploy/commands

params:
  actions:
    Commands:
      deploy:
        post_blocks:
          dev:
            params:
              actions:
                - 'npm install'
                - 'npm run build'
  containers:
    common:
      deploy:
        commands:
          params:
            post_blocks:
              - actions:
                - from: .params.actions.Commands.deploy.post_blocks.${context.environment}.execute
