---
jobs:
  dev:
    from:
      - .params.jobs.folder.dev
      - .params.jobs.folder.helm.general.install
    jobs:
      install:
        from:
          # - .params.jobs.common.helm.install
          - .params.jobs.gitlab.triggers.push.develop
          - .params.jobs.gitlab.webhooks.push

  preprod:
    from:
      - .params.jobs.folder.preprod
      - .params.jobs.folder.helm.general.install

  prod:
    from:
      - .params.jobs.folder.prod
      - .params.jobs.folder.helm.general.install

  merge-requests:
    from: .params.jobs.folder.mr
    jobs:
      status:
        from: .params.jobs.common.helm.status

      install:
        from:
          - .params.jobs.common
          - .params.jobs.gitlab.mr
          - .params.jobs.gitlab.triggers.mr
          - .params.jobs.gitlab.webhooks.mr
        pipeline:
          post_pods:
            - from: .params.pods.master
              containers:
                - from: .params.containers.common
                  blocks:
                    - from: .params.blocks.gitlab.accept-mr
          final_pods:
            # TODO: add clean slaves kubectl command here.
            - from: .params.pods.default
              containers:
                - from: .params.containers.helm.destroy

      destroy:
        from: .params.jobs.common.helm.destroy

  # stable-bump:
    # from:
      # - .params.jobs.common.bump_stable
      # - .params.jobs.gitlab.triggers.push.master
      # - .params.jobs.gitlab.webhooks.push
