---
scenarios:
  - root/environments/prod

environments:
  prod:
    deploy_target: git_target
    tagger:
      enabled: true
      handler: :option

components:
  master:
    states:
      stable:
        source:
          type: :retrieve_from_repo
          repo: :project_repo
          branch: state_stable
          file: info.yaml

deploy_targets:
  git_target:
    states:
      stable: prod
