---
params:
  containers:
    common:
      deploy:
        override: true
        params:
          blocks:
          - actions:
            - from: .params.actions.Commands.deploy.${context.environment}.execute
