params:
  pipelines:
    state:
      development:
        params:
          pods:
          - from: .params.pods.state.development
      staging:
        params:
          pods:
          - from: .params.pods.state.staging

      stable:
        params:
          pods:
          - from: .params.pods.state.stable

    release-build:
      params:
        pods:
        - from: .params.pods.release-build

    release-deploy:
      params:
        pods:
        - from: .params.pods.release-deploy
