---
from:
  - v2/params/pods

params:
  pipelines:
    state:
      development:
        params:
          pods:
          - from: .params.pods.state.development

      staging:
        params:
          pods:
          - from: .params.pods.state.staging

      migrate:
        params:
          pods:
          - from: .params.pods.state.migrate

      stable:
        params:
          pods:
          - from: .params.pods.state.stable

    release:
      full:
        development:
          params:
            pods:
              - from: .params.pods.release.full.development
        staging:
          params:
            pods:
              - from: .params.pods.release.full.staging
      build:
        params:
          pods:
            - from: .params.pods.release.build

      deploy:
        dev:
          params:
            pods:
              - from: .params.pods.release.deploy.dev

        stage:
          params:
            pods:
              - from: .params.pods.release.deploy.stage

        migrate:
          params:
            pods:
              - from: .params.pods.release.deploy.migrate

        preprod:
          params:
            pods:
            - from: .params.pods.release.deploy.preprod

        prod:
          params:
            pods:
            - from: .params.pods.release.deploy.prod
    test:
      taurus:
        params:
          pods:
            - from: .params.pods.test.taurus
      vegeta:
        params:
          pods:
            - from: .params.pods.test.vegeta
    backmerge:
      params:
        pods:
          - from: .params.pods.backmerge
    bump:
      stable:
        params:
          pods:
            - from: .params.pods.bump.stable
