---
from:
  - root
  - tools/skaffold/blocks
  - tools/skaffold/jobs

tags:
  - single
  - skaffold

params:
  actions:
    GCloud:
      params:
        cluster_name: main
        access_key_file_id: GCLOUD_ACCESS_KEY

  jobs:
    folder:
      skaffold:
        general:
          install:
            params:
              jobs:
                status:
                  from: .params.jobs.common.skaffold.status
                install:
                  from:
                    - .params.jobs.common
                  pipeline:
                    from: .params.pipelines.skaffold.install
                destroy:
                  from: .params.jobs.common.skaffold.destroy
    common:
      bump_stable:
        params:
          pipeline:
            from: .params.pipelines.bump_stable

      skaffold:
        install:
          params:
            pipeline:
              from: .params.pipelines.skaffold.install

        status:
          params:
            pipeline:
              from: .params.pipelines.skaffold.status

        destroy:
          params:
            pipeline:
              from: .params.pipelines.skaffold.destroy

    gitlab:
      params:
        name: 'jobs.gitlab'
      mr:
        params:
          branch: "${GIT_COMMIT}"

      webhooks:
        push:
          params:
            webhooks:
              - push_events: true
        mr:
          params:
            webhooks:
              - push_events: false
                merge_requests_events: true

      triggers:
        push:
          params:
            triggers:
              gitlabPush:
                buildOnPushEvents: true
                buildOnMergeRequestEvents: false
                enableCiSkip: true
          develop:
            params:
              triggers:
                gitlabPush:
                  includeBranches: ['develop']
          master:
            params:
              triggers:
                gitlabPush:
                  includeBranches: ['master']
        mr:
          params:
            triggers:
              gitlabPush:
                buildOnPushEvents: false
                rebuildOpenMergeRequest: 'source'
                includeBranches: ['master']
                enableCiSkip: true

  pipelines:
    params:
      name: default

    bump_stable:
      params:
        pods:
        - from: .params.pods.default
          containers:
          - from: .params.containers.common
            blocks:
            - from: .params.blocks.bump-stable

    skaffold:
      status:
        params:
          pods:
          - from: .params.pods.skaffold
            containers:
            - from: .params.containers.skaffold.status
            - from: .params.containers.kubectl.status

      install:
        params:
          pods:
          - from: .params.pods.skaffold
            containers:
            - from: .params.containers.skaffold
              blocks:
              - from: .params.blocks.skaffold.${context.container_types.kubectl.apply.type}.apply
              - from: .params.blocks.skaffold.status

      destroy:
        params:
          pods:
          - from: .params.pods.skaffold.destroy
  pods:
    skaffold:
      params:
        pre_containers:
        - from: .params.containers.gcloud
          blocks:
          - from: .params.blocks.gcloud.auth

      destroy:
        params:
          containers:
          - from: .params.containers.skaffold.destroy

  containers:
    gcloud:
      params:
        name: gcloud
        image: google/cloud-sdk:alpine
      auth:
        params:
          blocks:
            - from: .params.blocks.gcloud.auth

    kubectl:
      params:
        name: kubectl
        image: lachlanevenson/k8s-kubectl:v1.8.2

      status:
        params:
          blocks:
            - from: .params.blocks.kubectl.status

    skaffold:
      params:
        name: skaffold
        image: gcr.io/k8s-skaffold/skaffold

      status:
        params:
          blocks:
            - from: .params.blocks.skaffold.status

      destroy:
        params:
          blocks:
            - from: .params.blocks.skaffold.destroy
