---
scenarios:
  - root/environments/stage

environments:
  stage:
    deploy_target: git_target

components:
  master:
    states:
      staging:
        type: branch
        version: staging

deploy_targets:
  git_target:
    states:
      staging: stage
