---
scenarios:
  - roles/docman
  - roles/one-to-one/states/development
  - roles/one-to-one/states/staging
  - roles/one-to-one/states/stable
  - handlers/deploy/ansible
  - handlers/operations/yaml

components:
  master:
    type: root_chain
