---
scenarios:
  - roles/docman/environments/migrate

components:
  master:
    states:
      migrate:
        type: branch
        version: migrate

deploy_targets:
  git_target:
    states:
      migrate: migrate
