jobs:
  stable-bump:
    from:
      - .params.jobs.common.bump_stable

params:
  pipelines:
    bump_stable:
      params:
        pods:
        - from: .params.pods.default
          containers:
          - from: .params.containers.common
            blocks:
            - from: .params.blocks.bump-stable
  jobs:
    common:
      bump_stable:
        params:
          pipeline:
            from: .params.pipelines.bump_stable
  blocks:
    bump-stable:
      params:
        actions:
        - from: .params.actions.Docman.bumpStable
