from:
  - v2/params/pipelines

test:
  param1: jobs

params:
  jobs:
    state:
      params:
        type: state
      development:
        params:
          state: development
          env: dev
          branch: develop
          pipeline:
            from: .params.pipelines.state.development

      staging:
        params:
          state: staging
          env: stage
          branch: staging
          pipeline:
            from: .params.pipelines.state.staging

      stable:
        params:
          state: stable
          env: prod
          branch: master
          pipeline:
            from: .params.pipelines.state.stable

    release:
      build:
        params:
          type: release-build
          pipeline:
            from: .params.pipelines.release.build

      deploy:
        params:
          type: release-deploy
          source:
            type: tags
            pattern: stable-*
        preprod:
          params:
            env: preprod
            pipeline:
              from: .params.pipelines.release.deploy.preprod
        prod:
          params:
            env: prod
            pipeline:
              from: .params.pipelines.release.deploy.prod
