from:
  - v2/params/pipelines

params:
  jobs:
    state:
      params:
        type: state
      development:
        params:
          state: development
          env: dev
          branch: develop
          pipeline:
            from: .params.pipelines.state.development

      staging:
        params:
          state: staging
          env: stage
          branch: staging
          pipeline:
            from: .params.pipelines.state.staging

      stable:
        params:
          state: stable
          env: prod
          branch: master
          pipeline:
            from: .params.pipelines.state.stable

    release:
      build:
        params:
          type: release-build
          pattern: "*"
          pipeline:
            from: .params.pipelines.release.build

        development:
          params:
            state: development
            pattern: "develop"

        staging:
          params:
            state: staging
            pattern: "staging"

        stable:
          params:
            state: stable
            pattern: "stable--*"

      deploy:
        params:
          type: release-deploy
          source:
            type: tags
            pattern: stable-*

        dev:
          params:
            env: dev
            source:
              type: branches
              pattern: develop
            pipeline:
              from: .params.pipelines.release.deploy.dev

        stage:
          params:
            env: stage
            source:
              type: branches
              pattern: staging
            pipeline:
              from: .params.pipelines.release.deploy.stage

        preprod:
          params:
            env: preprod
            pipeline:
              from: .params.pipelines.release.deploy.preprod

        prod:
          params:
            env: prod
            pipeline:
              from: .params.pipelines.release.deploy.prod
