from:
  - v2/params/pipelines

params:
  jobs:
    state-development:
      params:
        type: state
        state: development
        env: dev
        branch: develop
        pipeline:
          from: .params.pipelines.state
    state-staging:
      params:
        type: state
        state: staging
        env: stage
        branch: staging
        pipeline:
          from: .params.pipelines.state
    state-stable:
      params:
        type: state
        state: stable
        env: prod
        branch: master
        pipeline:
          from: .params.pipelines.state-stable
    release-build:
      params:
        type: release-build
        pipeline:
          from: .params.pipelines.release-build
    release-deploy:
      params:
        env: prod
        type: release-deploy
        pipeline:
          from: .params.pipelines.release-deploy
        source:
          type: tags
          pattern: stable-*
