from:
  - v2/params/pipelines

params:
  jobs:
    state:
      params:
        type: state
      development:
        params:
          state: development
          env: dev
          branch: develop
          pipeline:
            from: .params.pipelines.state.development

      staging:
        params:
          state: staging
          env: stage
          branch: staging
          pipeline:
            from: .params.pipelines.state.staging

      migrate:
        params:
          state: migrate
          env: migrate
          branch: migrate
          pipeline:
            from: .params.pipelines.state.migrate

      stable:
        params:
          state: stable
          env: prod
          branch: master
          pipeline:
            from: .params.pipelines.state.stable

    release:
      full:
        params:
          type: release-build
          pattern: "*"
        development:
          params:
            state: development
            pipeline:
              from: .params.pipelines.release.full.development
        staging:
          params:
            state: staging
            pipeline:
              from: .params.pipelines.release.full.staging
      build:
        params:
          type: release-build
          pattern: "*"
          pipeline:
            from: .params.pipelines.release.build

        development:
          params:
            state: development
            pattern: "develop"

        staging:
          params:
            state: staging
            pattern: "staging"

        migrate:
          params:
            state: migrate
            pattern: "migrate"

        stable:
          params:
            state: stable

      deploy:
        params:
          type: release-deploy
          source:
            type: tags
            pattern: stable-*

        dev:
          params:
            env: dev
            source:
              type: branches
              pattern: develop
            pipeline:
              from: .params.pipelines.release.deploy.dev

        stage:
          params:
            env: stage
            source:
              type: branches
              pattern: staging
            pipeline:
              from: .params.pipelines.release.deploy.stage

        migrate:
          params:
            env: migrate
            source:
              type: branches
              pattern: migrate
            pipeline:
              from: .params.pipelines.release.deploy.migrate

        preprod:
          params:
            env: preprod
            pipeline:
              from: .params.pipelines.release.deploy.preprod

        prod:
          params:
            env: prod
            pipeline:
              from: .params.pipelines.release.deploy.prod
    test:
      taurus:
        params:
          type: common
          params:
            taurus_config: ""
            taurus_args: ""
            taurus_concurrency: "1"
            taurus_hold_for: "10"
            taurus_ramp_up: "1"
            taurus_throughput: "1"
            taurus_steps: "1"
          pipeline:
            from: .params.pipelines.test.taurus
      vegeta:
        params:
          type: common
          params:
            vegeta_prepare_command: ""
            vegeta_args: ""
            vegeta_connections: ""
            vegeta_duration: "10s"
            vegeta_redirects: ""
            vegeta_rate: "1"
            vegeta_timeout: ""
            vegeta_workers: ""
            vegeta_insecure: ""
            vegeta_keepalive: ""
            vegeta_lazy: ""
          pipeline:
            from: .params.pipelines.test.vegeta
    backmerge:
      params:
        type: common
        pipeline:
          from: .params.pipelines.backmerge
    bump:
      stable:
        params:
          type: common
          params:
            project_name: master
            branch: master
            tag: ''
          pipeline:
            from: .params.pipelines.bump.stable
