from:
  - v2/params/pipelines

params:
  jobs:
    state:
      development:
        params:
          type: state
          state: development
          env: dev
          branch: develop
          pipeline:
            from: .params.pipelines.state.development

      staging:
        params:
          type: state
          state: staging
          env: stage
          branch: staging
          pipeline:
            from: .params.pipelines.state.staging

      stable:
        params:
          type: state
          state: stable
          env: prod
          branch: master
          pipeline:
            from: .params.pipelines.state.stable

    release-build:
      params:
        type: release-build
        pipeline:
          from: .params.pipelines.release-build

    release-deploy-preprod:
      params:
        env: prod
        type: release-deploy
        pipeline:
          from: .params.pipelines.release-deploy-preprod
        source:
          type: tags
          pattern: stable-*

    release-deploy-prod:
      params:
        env: prod
        type: release-deploy
        pipeline:
          from: .params.pipelines.release-deploy-prod
        source:
          type: tags
          pattern: stable-*
