---
params:
  containers:
    common:
      deploy:
        commands:
          params:
            name: deploy-commands
            blocks:
              actions:
              - from: .params.actions.Commands.deploy.${context.environment}.execute
      operations:
        commands:
          params:
            name: operations-commands
            blocks:
              actions:
              - from: .params.actions.Commands.operations.${context.environment}.execute

