params:
  pods:
    state:
      params:
        containers:
          - from: .params.containers.common.build
          - from: .params.containers.common.deploy
          - from: .params.containers.common.operations.{$context.operations_type}

    state-stable:
      params:
        containers:
          - from: .params.containers.common.build

    release-build:
      params:
        containers:
          - from: .params.containers.common.build

    release-deploy:
      params:
        containers:
          - from: .params.containers.common.deploy
          - from: .params.containers.common.operations
