---
params:
  blocks:
    kubectl:
      status:
        params:
          actions:
          - from: .params.actions.Kubectl.get_pods

      pod-logs:
        params:
          actions:
          - from: .params.actions.Kubectl.get_pod_name
          - from: .params.actions.Kubectl.get_pod_logs
            pod_name: "${context.results.action.Kubectl_get_pod_name.stdout}"

    gcloud:
      auth:
        params:
          actions:
          - from: .params.actions.GCloud.auth

    skaffold:
      # params:
        # pre_actions:
        # - from: .params.actions.skaffold.init

      status:
        params:
          actions:
          - from: .params.actions.skaffold.status

      apply:
        params:
          actions:
          - from: .params.actions.skaffold.run

      destroy:
        params:
          actions:
          - from: .params.actions.skaffold.delete
