---
params:
  blocks:
    kubectl:
      status:
        params:
          actions:
          - from: .params.actions.Kubectl.get_pods

    gcloud:
      auth:
        params:
          actions:
          - from: .params.actions.GCloud.auth

    skaffold:
      status:
        params:
          actions:
          - from: .params.actions.Skaffold.status

      run:
        params:
          actions:
          - from: .params.actions.Helm.status

      destroy:
        params:
          actions:
          - from: .params.actions.Skaffold.delete
