from:
  - v2/options/deploy/commands/drupal

params:
  actions:
    Commands:
      deploy:
        post_blocks:
          dev:
            params:
              actions:
                - 'composer install --prefer-dist --optimize-autoloader'
          stage:
            params:
              actions:
                - 'composer install --prefer-dist --optimize-autoloader'
