---
params:
  containers:
    common:
      operations:
        params:
          name: operations
          blocks:
          - actions:
            - from: .params.actions.YamlFileHandler.operations
              name: YamlFileHandler
              methodName: operations

tags:
  - yaml
