---
params:
  containers:
    common:
      operations:
        params:
          name: operations
          blocks:
          - from: .params.blocks.operations.${context.block_operations_type}.${context.environment}

