---
# params:
  # containers:
    # common:
      # operations:
        # params:
          # name: operations
          # blocks:
          # - from: .params.blocks.operations.${context.block_operations_type}.${context.environment}
params:
  containers:
    common:
      operations:
        commands:
          params:
            name: operations-commands
            blocks:
              actions:
              - from: .params.actions.Commands.operations.${context.environment}.execute

