---
pipeline_script: .pipeline

environments:
  local:
    server: local
  test:
    git_reference: staging

tags:
  - drupipe

contexts:
  environment:
    inject_from: environments
  project:
    inject_from: projects
  component:
    inject_from: components
  state:
    inject_from: components.master.states

