---
params:
  containers:
    common:
      operations:
        commands:
          params:
            name: operations-commands
            blocks:
              actions:
              - from: .params.actions.Commands.operations.${context.environment}.execute

tags:
  - operations-commands
