---
params:
  containers:
    common:
      operations:
        params:
          name: operations-commands
          blocks:
          - from: .params.blocks.operations.commands

tags:
  - operations-commands
