---
from:
  - v2/params/containers

params:
  pods:
    state:
      development:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.development.type}.development
          - from: .params.containers.common.artifact.${context.container_types.artifact.development.type}.development
          - from: .params.containers.common.deploy.${context.container_types.deploy.development.type}.development
          - from: .params.containers.common.operations.${context.container_types.operations.development.type}.development
          - from: .params.containers.common.test.${context.container_types.test.development.type}.development

      staging:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.staging.type}.staging
          - from: .params.containers.common.artifact.${context.container_types.artifact.staging.type}.staging
          - from: .params.containers.common.deploy.${context.container_types.deploy.staging.type}.staging
          - from: .params.containers.common.operations.${context.container_types.operations.staging.type}.staging
          - from: .params.containers.common.test.${context.container_types.test.staging.type}.staging

      migrate:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.migrate.type}.migrate
          - from: .params.containers.common.artifact.${context.container_types.artifact.migrate.type}.migrate
          - from: .params.containers.common.deploy.${context.container_types.deploy.migrate.type}.migrate
          - from: .params.containers.common.operations.${context.container_types.operations.migrate.type}.migrate
          - from: .params.containers.common.test.${context.container_types.test.migrate.type}.migrate

      stable:
        params:
          containers:
          - from: .params.containers.common.build.${context.container_types.build.stable.type}.stable

    release:
      full:
        development:
          params:
            containers:
            - from: .params.containers.common.build.${context.container_types.build.release.full.development.type}.release.full.development
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.full.development.type}.release.full.development
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.full.development.type}.release.full.development
            - from: .params.containers.common.operations.${context.container_types.operations.release.full.development.type}.release.full.development
            - from: .params.containers.common.test.${context.container_types.test.release.full.development.type}.release.full.development
        staging:
          params:
            containers:
            - from: .params.containers.common.build.${context.container_types.build.release.full.staging.type}.release.full.staging
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.full.staging.type}.release.full.staging
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.full.staging.type}.release.full.staging
            - from: .params.containers.common.operations.${context.container_types.operations.release.full.staging.type}.release.full.staging
            - from: .params.containers.common.test.${context.container_types.test.release.full.staging.type}.release.full.staging
      build:
        params:
          containers:
            - from: .params.containers.common.build.${context.container_types.build.release.build.type}.release.build

      deploy:
        dev:
          params:
            containers:
              - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.dev.type}.release.deploy.dev
              - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.dev.type}.release.deploy.dev
              - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.dev.type}.release.deploy.dev
              - from: .params.containers.common.test.${context.container_types.test.release.deploy.dev.type}.release.deploy.dev

        stage:
          params:
            containers:
              - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.stage.type}.release.deploy.stage
              - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.stage.type}.release.deploy.stage
              - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.stage.type}.release.deploy.stage
              - from: .params.containers.common.test.${context.container_types.test.release.deploy.stage.type}.release.deploy.stage

        migrate:
          params:
            containers:
              - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.migrate.type}.release.deploy.migrate
              - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.migrate.type}.release.deploy.migrate
              - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.migrate.type}.release.deploy.migrate
              - from: .params.containers.common.test.${context.container_types.test.release.deploy.migrate.type}.release.deploy.migrate

        preprod:
          params:
            containers:
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.preprod.type}.release.deploy.preprod
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.preprod.type}.release.deploy.preprod
            - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.preprod.type}.release.deploy.preprod
            - from: .params.containers.common.test.${context.container_types.test.release.deploy.preprod.type}.release.deploy.preprod

        prod:
          params:
            containers:
            - from: .params.containers.common.artifact.${context.container_types.artifact.release.deploy.prod.type}.release.deploy.prod
            - from: .params.containers.common.deploy.${context.container_types.deploy.release.deploy.prod.type}.release.deploy.prod
            - from: .params.containers.common.operations.${context.container_types.operations.release.deploy.prod.type}.release.deploy.prod
            - from: .params.containers.common.test.${context.container_types.test.release.deploy.prod.type}.release.deploy.prod

    test:
      taurus:
        params:
          containers:
            - from: .params.containers.common.test.taurus
      vegeta:
        params:
          containers:
            - from: .params.containers.common.test.vegeta
    backmerge:
      params:
        containers:
          - from: .params.containers.common.backmerge
    bump:
      stable:
        params:
          containers:
            - from: .params.containers.common.bump.stable

