---
from:
  - helm/blocks
  - helm/jobs

tags:
  - single
  - helm

pipeline_script_full: Jenkinsfile

params:
  actions:
    GCloud:
      params:
        cluster_name: main
        access_key_file_id: GCLOUD_ACCESS_KEY

  jobs:
    folder:
      helm:
        general:
          install:
            params:
              jobs:
                status:
                  from: .params.jobs.common.helm.status
                install:
                  from:
                    - .params.jobs.common
                  pipeline:
                    from: .params.pipelines.helm.install
                destroy:
                  from: .params.jobs.common.helm.destroy
    common:
      bump_stable:
        params:
          pipeline:
            from: .params.pipelines.bump_stable

      helm:
        install:
          params:
            pipeline:
              from: .params.pipelines.helm.install

        status:
          params:
            pipeline:
              from: .params.pipelines.helm.status

        destroy:
          params:
            pipeline:
              from: .params.pipelines.helm.destroy

    gitlab:
      params:
        name: 'jobs.gitlab'
      mr:
        params:
          branch: "${GIT_COMMIT}"

      webhooks:
        push:
          params:
            webhooks:
              - push_events: true
        mr:
          params:
            webhooks:
              - push_events: false
                merge_requests_events: true

      triggers:
        push:
          params:
            triggers:
              gitlabPush:
                buildOnPushEvents: true
                buildOnMergeRequestEvents: false
                enableCiSkip: true
          develop:
            params:
              triggers:
                gitlabPush:
                  includeBranches: ['develop']
          master:
            params:
              triggers:
                gitlabPush:
                  includeBranches: ['master']
        mr:
          params:
            triggers:
              gitlabPush:
                buildOnPushEvents: false
                rebuildOpenMergeRequest: 'source'
                includeBranches: ['master']
                enableCiSkip: true

  pipelines:
    params:
      name: default

    bump_stable:
      params:
        pods:
        - from: .params.pods.default
          containers:
          - from: .params.containers.common
            blocks:
            - from: .params.blocks.bump-stable

    helm:
      status:
        params:
          pods:
          - from: .params.pods.helm
            containers:
            - from: .params.containers.helm.status
            - from: .params.containers.kubectl.status

      install:
        params:
          pods:
          - from: .params.pods.helm
            containers:
            - from: .params.containers.helm
              blocks:
              - from: .params.blocks.helm.${context.container_types.helm.apply.type}.apply
              - from: .params.blocks.helm.status

      destroy:
        params:
          pods:
          - from: .params.pods.helm.destroy
  pods:
    helm:
      params:
        pre_containers:
        - from: .params.containers.gcloud
          blocks:
          - from: .params.blocks.gcloud.auth

      destroy:
        params:
          containers:
          - from: .params.containers.helm.destroy

  containers:
    gcloud:
      params:
        name: gcloud
        image: google/cloud-sdk:alpine
      auth:
        params:
          blocks:
            - from: .params.blocks.gcloud.auth

    kubectl:
      params:
        name: kubectl
        image: lachlanevenson/k8s-kubectl:v1.8.2

      status:
        params:
          blocks:
            - from: .params.blocks.kubectl.status

    helm:
      params:
        name: kubectl
        image: lachlanevenson/k8s-helm:v2.7.2

      status:
        params:
          blocks:
            - from: .params.blocks.helm.status

      destroy:
        params:
          blocks:
            - from: .params.blocks.helm.destroy
